### ISSUE TITLE
Bug in skaffold when setting up

### ISSUE THREAD

**Issue by YousofMersal** [YousofMersal/DM885_Project_DevSecOps#13]
### Steps to reproduce:

* On a clean system follow the instructions in README.MD in root folder.
* after `terraform apply`, in the services folder when running `skaffold dev` you get the error message `panic: interface conversion: util.VersionedConfig is *v2.SkaffoldConfig, not *latest.SkaffoldConfig` 

<details>
<summary> with the trace </summary>

```
panic: interface conversion: util.VersionedConfig is *v2.SkaffoldConfig, not *latest.SkaffoldConfig

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/parser.getConfigs({_, _}, {{0xc000bd7dc0, 0x3f}, {0x0, 0x0, 0x0}, {0x436c300, 0x0, 0x0}, ...}, ...)
	/tmpfs/src/github/skaffold/pkg/skaffold/parser/config.go:137 +0xa54
github.com/GoogleContainerTools/skaffold/pkg/skaffold/parser.GetConfigSet({_, _}, {{0x0, 0x0}, {0xc000659d90, 0xd}, {0x27f53bd, 0x3}, {0x0, 0x0}, ...})
	/tmpfs/src/github/skaffold/pkg/skaffold/parser/config.go:85 +0x1a8
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withFallbackConfig({_, _}, {_, _}, {{0x0, 0x0}, {0xc000659d90, 0xd}, {0x27f53bd, 0x3}, ...}, ...)
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/runner.go:110 +0x79
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runContext({_, _}, {_, _}, {{0x0, 0x0}, {0xc000659d90, 0xd}, {0x27f53bd, 0x3}, ...})
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/runner.go:82 +0x85
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.createNewRunner({_, _}, {_, _}, {{0x0, 0x0}, {0xc000659d90, 0xd}, {0x27f53bd, 0x3}, ...})
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/runner.go:62 +0x7b
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner({0x2d63cd8, 0xc0001460c0}, {0x2d0c520, 0xc00058c370}, 0xc000b3fad0)
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/runner.go:50 +0x83
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev({0x2d63cd8, 0xc0001460c0}, {0x2d0c520, 0xc00058c370})
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/dev.go:66 +0x1f3
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0x9b4420, {0xc000b3fb80, 0xc000b3fb58, 0x0})
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/commands.go:138 +0x66
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.applyPostRunHooks.func1(0xc000211080, {0x436cad8, 0x0, 0x0})
	/tmpfs/src/github/skaffold/cmd/skaffold/app/cmd/commands.go:185 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc000211080, {0x436cad8, 0x0, 0x0})
	/Users/kbuilder/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000998000)
	/Users/kbuilder/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/Users/kbuilder/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:911
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run({0x2d0b6e0, 0xc000196008}, {0x2d0b6e0, 0xc000196010})
	/tmpfs/src/github/skaffold/cmd/skaffold/app/skaffold.go:50 +0x2ad
main.main()
	/tmpfs/src/github/skaffold/cmd/skaffold/skaffold.go:49 +0x1e5
```
</details>

**Comment by YousofMersal** [comment]
@viktorstrate Er det en fejl du kan genkende? Jeg har ikke kunne nail down hvor den opstår henne eller hvad fra.

**Comment by viktorstrate** [comment]
Hvilken version af Skaffold bruger du? Jeg har version 2.0.1

**Comment by YousofMersal** [comment]
Ah det er nok grunden, jeg har v1.39.2 jeg vidste ikke der var en ny version ude.

Efter at havde updateret til 2.0.1 virker det :+1:

**Comment by viktorstrate** [comment]
Ja tror også den er ret ny version
